baseURL = "https://dmcdonagh.github.io/kierandoyle/"
languageCode = "en-us"
title = "Kieran Doyle"
theme = "hugo-serif-theme"
publishDir = "docs"

[params]
    google_analytics_id=""

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "aboutme"
    url = "/aboutme/"
    weight = 2

[[menu.main]]
	name = "Testimonials"
	url = "/testimonials/"
	weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
